-- Create temporary_items table for restaurant POS system
-- This table stores draft bill items before they are converted to final bills

CREATE TABLE IF NOT EXISTS temporary_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_id UUID NOT NULL, -- Changed to UUID to match tables.id
  table_name VARCHAR(255),
  section VARCHAR(100),
  item_id UUID, -- Changed to UUID to match menu_items.id (if it's UUID)
  item_name VARCHAR(255) NOT NULL,
  item_category VARCHAR(100),
  quantity INTEGER NOT NULL DEFAULT 1,
  price DECIMAL(10,2) NOT NULL,
  total DECIMAL(10,2) NOT NULL,
  device_id VARCHAR(255), -- Device identifier for locking mechanism
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_temporary_items_table_id ON temporary_items(table_id);
CREATE INDEX IF NOT EXISTS idx_temporary_items_device_id ON temporary_items(device_id);
CREATE INDEX IF NOT EXISTS idx_temporary_items_created_at ON temporary_items(created_at);

-- Add RLS (Row Level Security) policies
ALTER TABLE temporary_items ENABLE ROW LEVEL SECURITY;

-- Policy to allow all operations (for simplicity in this implementation)
-- In production, you might want to restrict based on user roles
DROP POLICY IF EXISTS "Allow all operations on temporary_items" ON temporary_items;
CREATE POLICY "Allow all operations on temporary_items" ON temporary_items
  USING (true)
  WITH CHECK (true);

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_temporary_items_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to automatically update updated_at
DROP TRIGGER IF EXISTS temporary_items_updated_at ON temporary_items;
CREATE TRIGGER temporary_items_updated_at
  BEFORE UPDATE ON temporary_items
  FOR EACH ROW
  EXECUTE FUNCTION update_temporary_items_updated_at();

-- Add foreign key constraints if tables exist
-- These are optional and depend on your existing table structure
DO $$
BEGIN
  -- Add foreign key to tables table if it exists
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'tables') AND 
     NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_temporary_items_table_id') THEN
    ALTER TABLE temporary_items ADD CONSTRAINT fk_temporary_items_table_id 
      FOREIGN KEY (table_id) REFERENCES tables(id) ON DELETE CASCADE;
  END IF;
  
  -- Add foreign key to menu_items table if it exists
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'menu_items') AND 
     NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_temporary_items_item_id') THEN
    ALTER TABLE temporary_items ADD CONSTRAINT fk_temporary_items_item_id 
      FOREIGN KEY (item_id) REFERENCES menu_items(id) ON DELETE CASCADE;
  END IF;
END $$;
